spring:
  application:
    name: java-list
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgres://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
logging:
  level:
    root: debug
